# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

template:
  - binary_sensor:
      # I'm probably asleep when home, with my phone on charge, and a focus set.
      - name: "Scotty Asleep"
        unique_id: scotty_asleep
        state: >
          {{ is_state('person.scotty', 'home')
          and states('sensor.scottys_iphone_battery_state') in ['Charging', 'Full']
          and is_state('binary_sensor.scottys_iphone_focus', 'on') }}
        icon: >
          {% if is_state('binary_sensor.scotty_asleep', 'on') %}
            mdi:bed
          {% else %}
            mdi:bed-empty
          {% endif %}

      # If Shadie is home, and his phone is on charge, he's probably sleeping.
      - name: "Shadie Asleep"
        unique_id: shadie_asleep
        state: >
          {{ is_state('person.shadie', 'home')
          and states('sensor.pixel_8_pro_battery_state') in ['charging', 'full'] }}
        icon: >
          {% if is_state('binary_sensor.shadie_asleep', 'on') %}
            mdi:bed
          {% else %}
            mdi:bed-empty
          {% endif %}

      # Bedroom occupancy sensor that doesn't trigger while anyone is sleeping.
      - name: "Bedroom Occupancy and Awake"
        unique_id: bedroom_occupancy_awake
        state: >
          {{ is_state('binary_sensor.bedroom_occupancy', 'on')
          and not is_state('binary_sensor.scotty_asleep', 'on')
          and not is_state('binary_sensor.shadie_asleep', 'on') }}
        device_class: occupancy
        icon: mdi:home-account

      # General Home occupancy sensor based on people.
      - name: "Household Occupancy"
        unique_id: household_occupancy
        state: >
          {{ is_state('person.scotty', 'home')
          or is_state('person.shadie', 'home') }}
        device_class: occupancy
        icon: mdi:home-account
