blueprint:
  name: Light Occupancy
  description: Turn a light on while a room is occupied
  domain: automation
  input:
    light:
      name: Light
      description: This light will be turned on.
      selector:
        entity:
          filter:
            - domain: light
    sensor:
      name: Sensor
      description: This is the occupancy sensor that will be used.
      selector:
        entity:
          filter:
            - domain: binary_sensor

triggers:
  - trigger: state
    entity_id: !input sensor
    to: null
  - trigger: sun
    event: sunset
    offset: "00:15:00"
  - trigger: numeric_state
    entity_id:
      - weather.forecast_home
    attribute: cloud_coverage
    above: 50

conditions: []

actions:
  - if:
      - condition: state
        entity_id: !input sensor
        state: "on"
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: "00:15:00"
          - condition: and
            conditions:
              - condition: sun
                after: sunrise
              - condition: numeric_state
                entity_id: weather.forecast_home
                attribute: cloud_coverage
                above: 50
    then:
      - action: light.turn_on
        target:
          entity_id: !input light
    else:
      - action: light.turn_off
        target:
          entity_id: !input light
mode: queued
