alias: Kitchen Home at Night
id: kitchen_home_at_night
description: >
  Turns on the entrance and kitchen counter lights when anyone comes home late
  at night.

mode: single

triggers:
  # When the first person arrives home, turn on the lights.
  - trigger: state
    entity_id: binary_sensor.home_occupancy
    to: "on"
  # But also turn on the lights if known people arrive home, even if the home
  # is otherwise already occupied.
  - trigger: zone
    entity_id:
      - person.scotty
      - person.shadie
    zone: zone.home
    event: enter

conditions:
  # Only at night.
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"

actions:
  # Turn on the entrance light and the kitchen counter (at 25%).
  # Assume that takes a few seconds.
  - action: light.turn_on
    target:
      entity_id: light.entrance
  - action: light.turn_on
    data:
      brightness_pct: 25
    target:
      entity_id: light.kitchen_counter
  - delay:
      seconds: 5

  # Keep the lights on for 15 minutes.
  # But if the kitchen counter state changes, assume that we should leave that
  # one alone, and don't turn it off since someone messed with it.
  - wait_for_trigger:
      - trigger: state
        entity_id: light.kitchen_counter
    timeout:
      minutes: 15
  - if:
      - "{{ not wait.completed }}"
    then:
      - action: light.turn_off
        target:
          entity_id: light.kitchen_counter

  # Either way, turn off the entrance light once the time is up.
  - delay: "{{ wait.remaining }}"
  - action: light.turn_off
    target:
      entity_id: light.entrance
